[server]
headless = true
address = "localhost"
port = 5000

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#6C63FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"