[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
# Modern 3D theme with vibrant colors
primaryColor = "#6C63FF"  # Vibrant purple for primary actions
backgroundColor = "#FFFFFF"  # Clean white background for light mode
secondaryBackgroundColor = "#F4F7FF"  # Subtle blue tint for card backgrounds
textColor = "#1E2A3A"  # Dark navy for text
font = "sans serif"  # Clean, modern font

[browser]
gatherUsageStats = false
